excavator_algorithm: equihash
excavator_deb_url: "https://github.com/nicehash/excavator/releases/download/v1.4.1a/excavator_1.4.1a-xenial0_amd64.deb"
excavator_index_url: "https://raw.githubusercontent.com/nicehash/excavator/master/web/index.html"
excavator_pool_url: "us1-zcash.flypool.org:3333"
excavator_wallet: "t1dc6wAPXQtCEm4m7q2nCgGLMbdU5yPo4Hp"
excavator_web_directory: "/opt/excavator/bin/web"
miner_directory: "/var/miner"
miner_group: miners
miner_user: miner
nvidia_package: "nvidia-390"
nvidia_ppa: "ppa:graphics-drivers/ppa"
