---

- name: Create {{ miner_group }} group
  group: name={{ miner_group }}

- name: Create {{ miner_user}} user
  user: name={{ miner_user }} group={{ miner_group }} system=yes

- name: Create {{ miner_directory }}
  file:
    group: "{{ miner_group }}"
    mode: 0755
    owner: "{{ miner_user }}"
    path: "{{ miner_directory }}"
    state: directory

- name: Install {{ nvidia_package }} driver
  apt: pkg={{ nvidia_package }} state=latest update_cache=yes
  notify: enable-all-gpus
  notify: cool-bits
  notify: separate-x-screens
  notify: allow-empty-initial-configuration

- name: Install Excavator deb
  apt: deb={{ excavator_deb }}

- name: Install json file
  template: src=miner.json.j2 dest=/var/miner/miner.json
  notify: restart miner

- name: Install script
  template: src=miner.sh.j2 dest=/usr/bin/miner mode=0755

- name: Create {{ excavator_web_directory }}
  file:
    group: "{{ miner_group }}"
    mode: 0755
    owner: "{{ miner_user }}"
    path: "{{ excavator_web_directory }}"
    state: directory

- name: Download index.html
  get_url:
    url: "{{ index_url }}"
    dest: "{{ excavator_web_directory }}"
    owner: "{{ miner_user }}"
    group: "{{ miner_group }}"
    mode: 0755

- name: Install systemd service
  template: src=miner.service.j2 dest=/etc/systemd/system/miner.service owner=root mode=0644
  notify: reload sysctl
  notify: enable miner
  notify: restart miner

- name: Install systemd timer
  template: src=miner.timer.j2 dest=/etc/systemd/system/miner.timer owner=root mode=0644
  notify: reload sysctl
  notify: enable miner
  notify: restart miner
